### PR TITLE
Huge refactor of the SmartApp - SUPPORTS EVERY CAPABILITY

### PR DESCRIPTION
**Pull request by stjohnjohnson**
Things to note:
 - SmartThings has crazy restrictions with Groovy
 - Cannot use closures in an object
 - Have not tested all the devices (I don't have them all)
 - Lookup for change from MQTT is VERY inefficient!!

### CODE REVIEW

**Comment by joelash** [comment]
:+1: This is about what I wanted to do! Thanks for beating me to it. 

I assume there would still be changes required similar to the branch I was working on to keep the armed states of an HA `alarm_control_panel` with SmartThings Smart Home Monitor?

**Comment by stjohnjohnson** [comment]
@joelash Sorry for the delay, so for your Smart Home Monitor PR, I'd love it if you could create an issue here and we can walk through the design.  I sadly haven't played with either HA's alarm or SmartThings monitor tool.  But I think you'll either need to continue to modify the bridge device type or make another custom device type that can support that back and forth communication via the SmartApp.

**Comment by jer** [comment]
:+1: huge change, but it reads a lot simpler despite the support for everything.

What does it do to the SmartApp UI?

**Comment by stjohnjohnson** [comment]
It is slow to load (I'm assuming it has to evaluate the code first) but
then you get TONS of options.
On Tue, Mar 8, 2016 at 22:38 Jeremiah Wuenschel <notifications@github.com>
wrote:

> [image: :+1:] huge change, but it reads a lot simpler despite the support
> for everything.
>
> What does it do to the SmartApp UI?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stjohnjohnson/smartthings-mqtt-bridge/pull/22#issuecomment-194140283>
> .
>
-- 
-St. John

**Comment by jer** [comment]
I vote :shipit: but there may need to be an improvement later that lets us categorize stuff into pages or something

**Pull request merged**
