### PR TITLE
retain config option

### PR DESCRIPTION
**Pull request by b3nj1**
Hi,
For my application, I prefer not to retain state. In this PR, I've added a config option to retain or not.

mqtt:
  retain: false # true is default still

Please entertain merging.

Thanks,
Benjamin

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
Could you document the setting in the README file please

**Comment by b3nj1** [comment]
No problem. Done.

**Comment by stjohnjohnson** [comment]
+ smartthings-mqtt-bridge@1.4.0

**Comment by stjohnjohnson** [comment]
Thanks for the PR!!

**Pull request merged**
