### PR TITLE
notifications and sensors

### PR DESCRIPTION
**Pull request by joelash**
* send notifications through `mqtt.publish` to smart things mobile app
* smart sense multi-sensor has acceleration
* smart things app can be used as presence sensor

### CODE REVIEW

**Comment by jer** [comment]
Oh this is nice :+1:

**Comment by joelash** [comment]
I'm still adding different capabilities to this file as I need, I'm not sure what capabilities you would want in PRs or what you just want to leave out.

**Comment by jer** [comment]
Honestly I think we want any useful capability that can readily map to an
MQTT component. The more the merrier as long as we can keep the app config
relatively clean.

**Comment by joelash** [comment]
The cleanliness/repetition is what's starting to get to me. I haven't done a lot of groovy but I'd love to figure out how to reduce how many similar lines are required for one new capability... I'll get to that next

**Comment by stjohnjohnson** [comment]
Huge :+1: this looks awesome.

**Comment by stjohnjohnson** [comment]
@joelash if you want, we can merge this and then do a refactor.

**Comment by joelash** [comment]
@stjohnjohnson sounds great to me. I'll take a look at doing a refactor in the next couple of days. Unless you're already on it

**Comment by jer** [comment]
We are happy to have you tackle a refactor if you're interested

**Pull request merged**
