### PR TITLE
adding raspberry-pi specific Dockerfile

### PR DESCRIPTION
**Pull request by joelash**
Changed the from to a Arm based node container. I have this setup running on my Raspberry Pi presently.

### CODE REVIEW

**Comment by jer** [comment]
Awww yeah, was just talking about needing this yesterday with @chilicheech

:+1:

**Comment by stjohnjohnson** [comment]
:+1: :ship: :it: 
yes

**Comment by stjohnjohnson** [comment]
I just configured hub.docker to build the /Dockerfile-rpi and push it as `:latest-pi`: https://hub.docker.com/r/stjohnjohnson/smartthings-mqtt-bridge/builds/b6g48rdhzg9xcmjbnuoetag/

**Comment by stjohnjohnson** [comment]
Looks like it failed :( https://hub.docker.com/r/stjohnjohnson/smartthings-mqtt-bridge/builds/bv97el2c7w2e99aadv4mbi8/

```
Starting to clone
Cloning into 'bv97el2c7w2e99aadv4mbi8'...
Cloning done
Starting Build
KernelVersion: 3.13.0-40-generic
Os: linux
BuildTime: Mon Oct 12 05:37:18 UTC 2015
ApiVersion: 1.20
Version: 1.8.3
GitCommit: f4bf5c7
Arch: amd64
GoVersion: go1.4.2
Starting build of index.docker.io/stjohnjohnson/smartthings-mqtt-bridge:latest-rpi...
Step 0 : FROM hypriot/rpi-node:4
 ---> ab1202e36b9d
Step 1 : MAINTAINER St. John Johnson <st.john.johnson@gmail.com> and Jeremiah Wuenschel <jeremiah.wuenschel@gmail.com>
 ---> Running in 91a404e270eb
 ---> a3c37ec68b29
Removing intermediate container 91a404e270eb
Step 2 : RUN mkdir -p /usr/src/app
 ---> Running in 935142fc949e
Removing intermediate container 935142fc949e
[8] System error: exec format error
```

**Comment by joelash** [comment]
Looks like dockers hub doesn't build it on an ARM processor. Had I thought about it I could have guessed that. Darn!


J

**Comment by joelash** [comment]
I've been looking into this blog post about how Resin.io recommends building an ARM docker image using docker hub. I haven't had enough :coffee: yet to fully follow it, but will spend some more time working on it. https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

**Pull request merged**
